### PR TITLE
fix: Fixup most active contributors call

### PR DESCRIPTION
**Pull request by jpmcb**
## Description

This is PR does a few things to fix the extremely inefficient `most-active-contributors` endpoint on the user lists stats service (which was causing general app slowdown and tablelocks for big lists):

- Removes sub-queries in favor of sole CTE expressions
- Counts total contributions from already returned entities (instead of making another call)
- Removes usage of subqueries in aggregating active/new/alum contributors in favor of filtering on the `users` common table expression

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Steps to QA

Run API locally with connection to timescale. Enter a list ID in the swagger frontend. Note speed of returned data:

Screenshot 2024-01-31 at 7 48 29 PM

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Looks good! There’s a couple warnings from the coding standard action that you might want to sort out.

**Comment by jpmcb** [comment]
Ah whoops, meant to mark this as draft while iron some of the rough edges out 👀

**Comment by jpmcb** [comment]
This is ready to go in: I'll wait abit for comment from the team, otherwise, I'll try to get this in soon so we don't have another accidental bricking of the database overnight

**Review by brandonroberts — APPROVED** [review]
That's a lot of CTEs!

**Comment by jpmcb** [comment]
Who knew CTEs were so efficient! 🏈

**Pull request merged**
