### PR TITLE
feat: upgrade nestjs to v10

### LINKED ISSUE #202: Feature: Upgrade Nestjs to v10
### Type of feature

🍕 Feature

### Current behavior

The current NestJS version is using the TypeScript compiler which is fine, but we can speed up builds and server starting times with a faster compiler.

### Suggested solution

NestJS v10 is using SWC with Nest CLI to significantly speed up your development process.
> **Note**  SWC is approximately x20 times faster than the default TypeScript compiler.

### Bumps

There are a lot of deps bumps and bug fixes and no big breaking changes.

NestJS packages:
- @nestjs/common (9.4.0) -> v10.0.0
- @nestjs/core (9.4.0) -> v10.0.0
- @nestjs/config (2.3.1) -> v3.0.0
- @nestjs/axios (2.0.0) -> v3.0.0
- @nestjs/platform-fastify (9.4.0) -> v10.0.0
- @nestjs/passport (9.0.3) -> v10.0.0
- @nestjs/swagger (6.3.0) -> v7.1.1
- @nestjs/terminus (9.2.2) -> v10.0.1
- @nestjs/typeorm (9.0.1) -> v10.0.0
- nestjs-pino (3.2.0) -> v3.3.0
- @nestjs/cli (dev-dep)(9.4.2) -> v10.1.8
- @nestjs/schematics (dev-dep)(9.1.0) -> v10.0.1
- @nestjs/testing (dev-dep)(9.4.0) -> v10.0.5

Others:
- typeorm (0.3.15) -> v0.3.17
- @swc/core (dev-dep)(1.3.56) -> v1.3.61

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by takanome-dev**
## Description

This pr upgrades NestJS to v10.

- Breakings
  - `@ApiModelProperty` is now `@ApiProperty`
  - `@ApiModelPropertyOptional` is now `@ApiPropertyOptional`
  - Each relation now should be wrapper into `Relation` imported from `typeorm` (see https://docs.nestjs.com/recipes/swc#common-pitfalls)
  
<details>
<summary>Example</summary>

```ts
@Entity()
export class User {
  @OneToOne(() => Profile, (profile) => profile.user)
  profile: Relation<Profile>; // <--- see "Relation<>" type here instead of just "Profile"
}
```

</details>

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [x] 🤖 Build
- [x] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #202
## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by takanome-dev** [comment]
Wondering why SWC is type-checking the dist folder even if it's excluded in the tsconfig file. THIS error is the only blocker for this pr (I think :sweat_smile: ). Any help is appreciated :pray: 

```sh
/home/takanome_dev/projects/oss/open-sauced/api.opensauced.pizza/dist/user/user.entity.js:8
        return DbUser;
        ^
ReferenceError: Cannot access 'DbUser' before initialization
    at Object.get [as DbUser] (/home/takanome_dev/projects/oss/open-sauced/api.opensauced.pizza/dist/user/user.entity.js:8:9)
    at Object.<anonymous> (/home/takanome_dev/projects/oss/open-sauced/api.opensauced.pizza/dist/repo/entities/repo.to.user.votes.entity.js:88:52)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/takanome_dev/projects/oss/open-sauced/api.opensauced.pizza/dist/user/user.entity.js:14:32)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
^C
``

**Comment by brandonroberts** [comment]
@takanome-dev will you update this PR? Have some time to check into this more

**Comment by takanome-dev** [comment]
> @takanome-dev will you update this PR? Have some time to check into this more

@brandonroberts Thanks for the heads up :+1: Yeah, it was an issue with `swc`. By default, it was compiling to `esm` which was causing that issue. I changed it to `es5` and it works.

Just need to fix CI test failing here

**Comment by jpmcb** [comment]
Hi @takanome-dev - thanks for this!! This overall looks solid, can you fix the merge conflicts? I'd be happy to dedicate some cycles to getting this in 👍🏼

**Comment by nickytonline** [comment]
> > @takanome-dev will you update this PR? Have some time to check into this more
> 
> 
> 
> @brandonroberts Thanks for the heads up :+1: Yeah, it was an issue with `swc`. By default, it was compiling to `esm` which was causing that issue. I changed it to `es5` and it works.
> 
> 
> 
> Just need to fix CI test failing here

Can it be a version higher than es5, like ES2021? If we use es5 it will polyfill a lot of things that are supported in Node.

**Comment by takanome-dev** [comment]
> Hi @takanome-dev - thanks for this!! This overall looks solid, can you fix the merge conflicts? I'd be happy to dedicate some cycles to getting this in 👍🏼

Done @jpmcb, thanks :+1:

**Comment by takanome-dev** [comment]
> Can it be a version higher than es5, like ES2021? If we use es5 it will polyfill a lot of things that are supported in Node.

Tried it and got the same issue as https://github.com/open-sauced/api/pull/206#issuecomment-1635574566

**Comment by nickytonline** [comment]
So this builds fine using `es2021` in the .swcrc file, but it fails at runtime.

```diff
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
-    "target": "es5",
+    "target": "es2021", 
    "baseUrl": "./"
  },
  "minify": false
}
```

It fails at runtime probably in multiple places but the first error I saw was accessing `DBRepo` before it was defined in the compiled code. Since we do `let DBRepo`, it's block scoped and defined at the line it's at and doesn't get [hoisted](https://www.freecodecamp.org/news/javascript-let-and-const-hoisting/) like it would if we're using es5.

```
Successfully compiled: 240 files with swc (70.61ms)

/Users/nicktaylor/dev/work/api/dist/repo/entities/repo.entity.js:8
        return DbRepo;
        ^
ReferenceError: Cannot access 'DbRepo' before initialization
    at Object.get [as DbRepo] (/Users/nicktaylor/dev/work/api/dist/repo/entities/repo.entity.js:8:9)
    at Object.<anonymous> (/Users/nicktaylor/dev/work/api/src/contribution/contribution.entity.ts:108:17)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/nicktaylor/dev/work/api/dist/repo/entities/repo.entity.js:14:29)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
```

Are we OK with going with ES5 for now?

**Comment by bdougie** [comment]
Closing this since it needs a lot of work to catch up.

**Pull request closed without merging**
