### PR TITLE
feat: Update Auto-Summarize Tool Description to First Person

### PR DESCRIPTION
**Pull request by SoundaryaKoutharapu**
## Description
 I have updated the auto-summarize tool's description to use first-person language to provide a smoother and more user-friendly experience

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [x] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes : open-sauced/app#1826

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
Renaming the file causes several imports to break:

```
src/blogs/issue-summary.controller.ts:6:36 - error TS2307: Cannot find module './issue-summary.service' or its corresponding type declarations.

6 import { BlogSummaryService } from "./issue-summary.service";
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~

src/blogs/issue-summary.module.ts:3:36 - error TS2307: Cannot find module './issue-summary.service' or its corresponding type declarations.

3 import { BlogSummaryService } from "./issue-summary.service";
```

can you fix the imports? Otherwise, this looks good

**Comment by SoundaryaKoutharapu** [comment]
@jpmcb  I understand that I need to update the import paths to match the new filename. I will proceed to make the necessary changes as you've suggested.
Once the changes are complete, I will inform you. 
ThanQ!

**Review by nickytonline — COMMENTED** [review]
This looks good to me as well. Once the imports are sorted as @jpmcb mentioned, this is good to go.

**Comment by SoundaryaKoutharapu** [comment]
Hi @jpmcb 
I have made the suggested changes
can you please review it?

**Review by jpmcb — APPROVED** [review]
Nice work!  Thanks for the contribution!!

**Pull request merged**
