### PR TITLE
feat: add campaign_start_date field to users table

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Adds `campaign_start_date` to users table
- Adds db migration
- Populates `campaign_start_date` for newly connected users

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Related to: #https://github.com/open-sauced/engineering/issues/214

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by nickytonline — COMMENTED** [review]
Looks good! One question. Is it possible to be a part of multiple campaigns, or are we only supporting one at a time atm?

**Comment by brandonroberts** [comment]
> Looks good! One question. Is it possible to be a part of multiple campaigns, or are we only supporting one at a time atm?



> Looks good! One question. Is it possible to be a part of multiple campaigns, or are we only supporting one at a time atm?

Good question. I thought about this also. I think if we were to support multiple campaigns simultaneously we'd probably look at using an external tool/service.

**Review by nickytonline — APPROVED** [review]
🚢

**Review by jpmcb — APPROVED** [review]
:shipit:

**Pull request merged**
