### PR TITLE
chore: release 2.8.0

### PR DESCRIPTION
**Pull request by jpmcb**

### CODE REVIEW

**Comment by jpmcb** [comment]
Validated this works on a beta build of the API conntected to the dev database (with the migrations applied) and my test user not included in the feature flagging:

Screenshot 2024-02-20 at 12 31 18 PM

Screenshot 2024-02-20 at 12 31 27 PM

Clicked around, created a workspace and a user list. Everything seems good.

---

CC @open-sauced/engineering - let me know if there's further validation we want!

**Review by nickytonline — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]
Also did a quick sanity check of the App on main against the API on beta without any issues. Was able to create/view insights/lists/highlights

**Comment by jpmcb** [comment]
Eating lunch, will merge/launch shortly!

**Pull request merged**
