### PR TITLE
feat: implements v2 histograms

### PR DESCRIPTION
**Pull request by jpmcb**
## Description

Adds a `v2/histogram/pushes` endpoint for generated histograms

Also refactors the stars DTO to use a common shared DTO.

Example:

```sh
curl -X 'GET' \
  'http://localhost:3003/v2/histogram/commits?range=30&repo=open-sauced%2Fapp' \
  -H 'accept: application/json'
```

```json5
[
  {
    "bucket": "2023-12-22T00:00:00.000Z",
    "pushes_count": 24
  },
  {
    "bucket": "2023-12-21T00:00:00.000Z",
    "pushes_count": 37
  },

  // redacted

  {
    "bucket": "2023-12-05T00:00:00.000Z",
    "pushes_count": 18
  },
  {
    "bucket": "2023-12-04T00:00:00.000Z",
    "pushes_count": 12
  }
]
```

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Related to #458 

## Mobile & Desktop Screenshots/Recordings

N/a

## Steps to QA

1. Run locally with timescale secrets
2. Access the `v2/histogram/pushes` endpoint

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by jpmcb** [comment]
Converting to draft: it actually won't be too big of a lift to just pound these each out in their own commit. Just added a commit for fork histograms 📈

**Comment by jpmcb** [comment]
This is ready to roll. It adds histograms for:

Screenshot 2024-01-02 at 7 07 53 PM

The data is relatively basic right now and only accepts a repo name to generate a histogram. But it's _lightning fast_ and and should unblock https://github.com/open-sauced/contributor.info/pull/19

```
❯ time curl -X 'GET' \
  'http://localhost:3003/v2/histogram/pull-requests?range=30&repo=open-sauced%2Fapp' \
  -H 'accept: application/json'
[{"bucket":"2024-01-03T00:00:00.000Z","prs_count":1},{"bucket":"2023-12-29T00:00:00.000Z","prs_count":2},{"bucket":"2023-12-27T00:00:00.000Z","prs_count":1},{"bucket":"2023-12-26T00:00:00.000Z","prs_count":1},{"bucket":"2023-12-22T00:00:00.000Z","prs_count":4},{"bucket":"2023-12-21T00:00:00.000Z","prs_count":7},{"bucket":"2023-12-20T00:00:00.000Z","prs_count":5},{"bucket":"2023-12-19T00:00:00.000Z","prs_count":7},{"bucket":"2023-12-18T00:00:00.000Z","prs_count":5},{"bucket":"2023-12-17T00:00:00.000Z","prs_count":1},{"bucket":"2023-12-16T00:00:00.000Z","prs_count":1},{"bucket":"2023-12-13T00:00:00.000Z","prs_count":3},{"bucket":"2023-12-12T00:00:00.000Z","prs_count":6},{"bucket":"2023-12-11T00:00:00.000Z","prs_count":3},{"bucket":"2023-12-10T00:00:00.000Z","prs_count":1},{"bucket":"2023-12-09T00:00:00.000Z","prs_count":1},{"bucket":"2023-12-08T00:00:00.000Z","prs_count":5},{"bucket":"2023-12-07T00:00:00.000Z","prs_count":5},{"bucket":"2023-12-06T00:00:00.000Z","prs_count":3},{"bucket":"2023-12-05T00:00:00.000Z","prs_count":4},{"bucket":"2023-12-04T00:00:00.000Z","prs_count":2}]curl -X 'GET'  -H 'accept: application/json' 

0.00s user 0.01s system 16% cpu 0.070 total
```

cc @bdougie let me know if there's anything else you see value here or that I missed!

**Comment by bdougie** [comment]
This is a great base layer for putting together exciting ways (i.e. contributor.info) to present this data. Having the flexibility of ranges is useful. We could punt on this, but it would be nice to have flexibility in the buckets. 

Currently, buckets are daily, but I could see a need to have weekly and quarterly buckets. But definitely punt on that.

**Comment by bdougie** [comment]
> Currently, buckets are daily, but I could see a need to have weekly and quarterly buckets. But definitely punt on that.

Actually, that could easily be done from the frontend.

**Review by bdougie — APPROVED** [review]
Would love someone else to do a technical review, but looking at the code and screenshots, this will be very useful

**Comment by jpmcb** [comment]
> I was under the impression that the entities needed to be added to the app.module.ts also?

Hmmm, good question. I thought generated entities did not get added to the top level app module. For example, a few in the `user-lists` module aren't added there:

https://github.com/open-sauced/api/blob/fe643e0b19dcd8aae9630fe67f006e96ff11269e/src/user-lists/entities/contributions-timeframe.entity.ts#L5

Maybe it's a soft requirement? Or maybe since they have `select: false` and `insert: false` it skips validating them ... ? Maybe worth some extra cycles to figure out the right thing to do

**Comment by brandonroberts** [comment]
Ok, I've just run into issues at runtime in the past with it not finding the metadata for those, but maybe its not a hard requirement.

**Comment by jpmcb** [comment]
@brandonroberts - Adding those entities to the app module results in:

```
[Nest] 7368  - 01/03/2024, 6:05:40 PM   ERROR [TypeOrmModule] Unable to connect to the database (ApiConnection). Retrying (2)...
MissingPrimaryColumnError: Entity "DbWatchGitHubEventsHistogram" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.
```

which I suppose makes sense since they _won't_ have a primary column: they're only ever generated by our routes.

Maybe there's something I'm missing but it seems we wouldn't want to add those entities for `ApiConnection` since they shouldn't have metadata loaded on them: they're "at query time" pieces of generated data.

The timescale tables also don't have primary columns: while the event ID is sort of unique, we didn't set that as a constraint on the database tables since there were key violations scattered throughout the data.

**Comment by brandonroberts** [comment]
@jpmcb Ahh I see now, these entities are more for structure and types instead of queryable entities.

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
