### PR TITLE
feat: Enable multi select for location and timezone

### PR DESCRIPTION
**Pull request by jpmcb**
## Description

Enables multiple location and timezone selection when searching for list contributors.

Cc @OgDev-01 

Sending a request for both `Denver, Colorado` and `Alabama` returns expected results:

```sh
curl -X 'GET' \
  'http://localhost:3003/v1/lists/contributors?page=1&limit=10&location=Denver%2C%20Colorado&location=Alabama&pr_velocity=2' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer <redacted>'
```

```json5
{
  "data": [
    {
      "id": 42211,
      "open_issues": 84,
      "created_at": "2008-12-23T09:43:29.000Z",
      "updated_at": "2023-09-25T20:24:38.969Z",
      "first_opened_pr_at": "2012-10-06T08:35:52.000Z",
      "first_pushed_commit_at": "2013-01-22T13:22:13.000Z",
      "connected_at": "2023-06-16T20:27:00.041Z",
      "node_id": "MDQ6VXNlcjQyMjEx",
      "avatar_url": "https://avatars.githubusercontent.com/u/42211?u=32763fc85100fa45c5aa5d4bdddc4344e53d0173&v=4",
      "gravatar_id": "",
      "url": "https://github.com/brandonroberts",
      "login": "brandonroberts",
      "is_private": false,
      "is_open_sauced_member": true,
      "is_onboarded": false,
      "is_waitlisted": false,
      "role": 50,
      "bio": "Web developer, @ngrx  maintainer, creator of @analogjs, GDE, sports ranter, and gif slinger. Head of Engineering @open-sauced .",
      "blog": "https://brandonroberts.dev",
      "name": "Brandon Roberts",
      "twitter_username": "brandontroberts",
      "linkedin_url": "https://www.linkedin.com/in/brandontroberts",
      "github_sponsors_url": "https://github.com/sponsors/brandonroberts",
      "discord_url": "",
      "company": "CodeSequence, LLC",
      "location": "Alabama",
      "display_local_time": true,
      "interests": "typescript",
      "hireable": false,
      "public_repos": 287,
      "public_gists": 69,
      "type": "User",
      "display_email": false,
      "receive_collaboration": true,
      "timezone": "Central Standard Time",
      "languages": {
        "CSS": 6959,
        "HTML": 3993,
        "JavaScript": 33713,
        "TypeScript": 170156
      }
    },
    {
      "id": 23109390,
      "open_issues": 80,
      "created_at": "2016-10-28T04:35:47.000Z",
      "updated_at": "2023-09-25T20:32:18.719Z",
      "first_opened_pr_at": "2016-10-28T04:55:11.000Z",
      "first_pushed_commit_at": "2023-08-29T20:04:59.000Z",
      "connected_at": "2023-06-22T04:20:11.989Z",
      "node_id": "MDQ6VXNlcjIzMTA5Mzkw",
      "avatar_url": "https://avatars.githubusercontent.com/u/23109390?u=385f5ea55c6a932878eed020c2f96111209d0d11&v=4",
      "gravatar_id": "",
      "url": "https://github.com/jpmcb",
      "login": "jpmcb",
      "is_private": false,
      "is_open_sauced_member": true,
      "is_onboarded": true,
      "is_waitlisted": false,
      "role": 50,
      "bio": "🍕",
      "blog": "https://johncodes.com",
      "name": "John McBride",
      "twitter_username": "johncodezzz",
      "linkedin_url": "",
      "github_sponsors_url": "",
      "discord_url": "",
      "company": "@open-sauced",
      "location": "Denver, Colorado",
      "display_local_time": true,
      "interests": "",
      "hireable": true,
      "public_repos": 147,
      "public_gists": 7,
      "type": "User",
      "display_email": false,
      "receive_collaboration": false,
      "timezone": "Mountain Standard Time",
      "languages": {
        "Go": 560938,
        "Lua": 23161,
        "HTML": 569,
        "Ruby": 799,
        "Shell": 994,
        "Makefile": 2188,
        "JavaScript": 256,
        "TypeScript": 137593
      }
    }
  ],
  "meta": {
    "page": 1,
    "limit": 10,
    "itemCount": 2,
    "pageCount": 1,
    "hasPreviousPage": false,
    "hasNextPage": false
  }
}
```

_Note: this is a direct search. So I must put in `Denver, Colorado` and `Alabama` to exactly match the `location` in a user's profile._

A future enhancement would be to make this "fuzzier" so that similar locations can be returned at once.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes: https://github.com/open-sauced/api/issues/326

Related to various list feature work in https://github.com/open-sauced/app/issues/1662

## Mobile & Desktop Screenshots/Recordings

N/a

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
This looks good to me. I'm just wondering about locations with a comma in it or do we assume those to be automatically two locations?

For example  If I typed in the input in the UI `London, Ontario`, would this look for all Londons, i.e. England and Canada? Or can we handle searching for a city with a province/state or Country?

As a user, I'd be expecting London in Canada only, and not even results in Ontario. This also might be a longer term thing for handling more than just a city name.

Hope I'm making that clear. 😅

**Comment by jpmcb** [comment]
> This looks good to me. I'm just wondering about locations with a comma in it or do we assume those to be automatically two locations?

Unfortunately, `location` in our data is not that granular: we pull it off of GitHub's location field for a user's profile and that is actually just a free text field. My location just so happens to be `Denver, Colorado` and using `Denver, Colorado` in the query matches that field exactly. But i could just as easily enter `Earth`. Or `Arkham Asylum`. Or `The Starship Enterprise`. Or something really silly like `...`. It's just a free text field and (as of today) we don't try to do any actual location validation on it: we sort of leave it up to the users (and trust them) to fill in a meaningful location there.

cc @isabensusan since this may affect how we think about the list features by location.

**Comment by OgDev-01** [comment]
I think we might need discussing deeper about the UI side of things with the location filters in our upcoming meeting as it kinda seems a bit off(to me) to be a select dropdown ATM cc: @nickytonline @isabensusan

**Comment by nickytonline** [comment]
> I think we might need discussing deeper about the UI side of things with the location filters in our upcoming meeting as it kinda seems a bit off(to me) to be a select dropdown ATM cc: @nickytonline @isabensusan

@OgDev-01, what's the associated UI issue for this? I can comment in there to compliment or sync later today.

**Comment by jpmcb** [comment]
Re-surfacing this @open-sauced/engineering: is this still blocked from the API side? I can see us shipping this PR and iterating as needed for the front-end's needs  :shipit:

**Comment by bdougie** [comment]
> Re-surfacing this @open-sauced/engineering: is this still blocked from the API side? I can see us shipping this PR and iterating as needed for the front-end's needs :shipit:

I am losing the thread on these changes, but I am curious if this is related. https://github.com/open-sauced/app/pull/1827#pullrequestreview-1662875596

Location search is not a priority at the moment, but I'd suggest we look into sanitizing location data via a google API as it was mentioned in the last eng sync.

**Comment by jpmcb** [comment]
I am loosing the thread on this abit too but the original ask was for the list-contributors API to be able to use filters for _multiple_ locations and timezones (not just 1 each, which is the current behavior).

**Comment by bdougie** [comment]
That does make more sense now.

**Review by bdougie — APPROVED** [review]
This aligns more with expectations and up. Ideally someone will be able to select multiple locations and time zones to narrow the search.

**Comment by brandonroberts** [comment]
@jpmcb is this still blocked?

**Comment by jpmcb** [comment]
No, we just need to decide if we need this still. Revisiting this now to get the merge conflict resolved 👀

**Comment by jpmcb** [comment]
This is ready to go: I had to add a `@Transform` to get nestjs to accept _both_ single value strings and arrays of strings. Otherwise, with single values, it complained that `location must be an array`:

```ts
@Transform(({ value }) => (Array.isArray(value) ? value : Array(value)) as string[], { toClassOnly: true })
```

**Review by nickytonline — APPROVED** [review]
:shipit:

**Comment by jpmcb** [comment]
@OgDev-01 - I'm not sure how this would exactly be implemented by the front end, but from how the query parameters work in swagger, it uses _multiple_ "location" selectors:

```
curl -X 'GET' \
  'http://localhost:3003/v1/lists/contributors?page=1&limit=10&location=Denver%2C%20Colorado&location=Germany' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer <redacted>'
```

In this request, it's making a request with two `location` params: one for "Denver, Colorado" and another for "Germany". Also note that the first one has a comma in it since the location field may have commas in it (remember, it's just a free text field from GitHub). 1 `location` query param still works fine, but if you provided `location` as a single string, it would take that as the entire string to use as the search query.

So, from your example, it would need to be something more like:
```go
location = []string{
  "lagos",
  "capetown",
  "newyork city",
}
```
where each member of that array is added as it's own `location` query param. Does that make sense?

**Comment by nickytonline** [comment]
> @OgDev-01 - I'm not sure how this would exactly be implemented by the front end, but from how the query parameters work in swagger, it uses _multiple_ "location" selectors:
> 
> ```
> curl -X 'GET' \
>   'http://localhost:3003/v1/lists/contributors?page=1&limit=10&location=Denver%2C%20Colorado&location=Germany' \
>   -H 'accept: application/json' \
>   -H 'Authorization: Bearer <redacted>'
> ```
> 
> In this request, it's making a request with two `location` params: one for "Denver, Colorado" and another for "Germany". Also note that the first one has a comma in it since the location field may have commas in it (remember, it's just a free text field from GitHub). 1 `location` query param still works fine, but if you provided `location` as a single string, it would take that as the entire string to use as the search query.
> 
> So, from your example, it would need to be something more like:
> 
> ```go
> location = []string{
>   "lagos",
>   "capetown",
>   "newyork city",
> }
> ```
> 
> where each member of that array is added as it's own `location` query param. Does that make sense?

We can discuss implementing it in the frontend @OgDev-01

**Comment by OgDev-01** [comment]
>  Does that make sense?

Yes... Thanks for the clarification 🍕

**Review by OgDev-01 — APPROVED** [review]

**Pull request merged**
